# Generated by Django 3.1.1 on 2020-09-21 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('iprice', models.DecimalField(decimal_places=2, max_digits=16)),
                ('idate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('url', models.URLField(blank=True)),
                ('des', models.TextField(blank=True)),
                ('status', models.IntegerField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemcategory', to='auctions.category')),
                ('iuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lister', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comment', models.TextField()),
                ('citem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentitem', to='auctions.item')),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bprice', models.DecimalField(decimal_places=2, max_digits=16)),
                ('bdate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('bitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biditem', to='auctions.item')),
                ('buser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
