# Generated by Django 3.1.1 on 2020-09-21 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='iwatch',
            field=models.ManyToManyField(blank=True, related_name='iwatchlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
