# Generated by Django 3.1.1 on 2020-09-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_item_iwatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ibid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=16),
            preserve_default=False,
        ),
    ]
