# Generated by Django 3.1.1 on 2021-03-30 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppost', models.TextField(max_length=1000)),
                ('pdate', models.DateTimeField(auto_now_add=True)),
                ('plikes', models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL)),
                ('puser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ffollowers', models.ManyToManyField(blank=True, related_name='ferslist', to=settings.AUTH_USER_MODEL)),
                ('ffollowings', models.ManyToManyField(blank=True, related_name='fingslist', to=settings.AUTH_USER_MODEL)),
                ('fuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
